language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.1
    - 7.2
    - master

addons:
  code_climate:
    repo_token: 5619fc9386e65aaf3b57e6978ea07726cbd3bd0ed9198e0811b1248ef371e959

before_install:
    - echo $HOSTNAME
    - export IS_HHVM=$(phpenv version | grep "hhvm" > /dev/null; echo $?)
    - echo $IS_HHVM

install:
    - composer update --no-interaction --no-suggest
    - sudo ./tests/provisioner/install_ejabberd.sh testuser testpass
    - sudo ./tests/provisioner/install_dovecot.sh testuser testpass

before_script:
    - cat tests/behat.yml.dist | sed "s/precise32/$HOSTNAME/" > tests/behat.yml

script:
    - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml --verbose
    - ./vendor/bin/behat -f progress

after_script:
    - ./tests/upload_artefacts.sh

after_failure:
    - cat tests/log/features/behat.*.log

matrix:
    fast_finish: true
